#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Export the FastAPI-generated OpenAPI document to docs/openapi.yaml.
#
# The spec is generated from the route signatures, so it cannot drift from the
# code. CI regenerates it and fails if the committed file is stale.
# ---------------------------------------------------------------------------
# shellcheck source=scripts/lib/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

PYTHON="${PYTHON:-$REPO_ROOT/.venv/bin/python}"
[[ -x "$PYTHON" ]] || PYTHON="$(command -v python3)"
OUTPUT="$REPO_ROOT/docs/openapi.yaml"

mkdir -p "$(dirname "$OUTPUT")"

log "Generating OpenAPI spec -> docs/openapi.yaml"

cd "$REPO_ROOT/app" || exit 1
APP_ENVIRONMENT=docs "$PYTHON" - "$OUTPUT" <<'PY'
import sys

import yaml

from main import app

spec = app.openapi()
with open(sys.argv[1], "w", encoding="utf-8") as handle:
    handle.write("# Generated by scripts/gen-openapi.sh — do not edit by hand.\n")
    handle.write("# Regenerate with: make openapi\n")
    yaml.safe_dump(spec, handle, sort_keys=False, width=100, allow_unicode=True)
PY

success "Wrote docs/openapi.yaml"
